{ 'arity': 2,
  'dptch': ['bool_', 'real_', 'arithmetic_'],
  'incld': [],
  'norst': False,
  'rnges': { 'default': [ ['nt2::Valmin<T>()/2', 'nt2::Valmax<T>()/2'],
                          ['nt2::Valmin<T>()', 'nt2::Valmax<T>()']],
             'double': [['-10.0', '10.0'], ['-10.0', '10.0']],
             'float': [['-10.0f', '10.0f'], ['-10.0f', '10.0f']]},
  'rturn': { 'default': 'typename boost::result_of<nt2::meta::arithmetic(T,T)>::type'},
  'specv': { 'default': { },
             'real_': { 'nt2::Inf<T>()': 'nt2::Nan<T>()',
                        'nt2::Minf<T>()': 'nt2::Nan<T>()',
                        'nt2::Mone<T>()': 'nt2::Zero<T>()',
                        'nt2::Nan<T>()': 'nt2::Nan<T>()',
                        'nt2::One<T>()': 'nt2::Zero<T>()',
                        'nt2::Zero<T>()': 'nt2::Zero<T>()'}, 
             'signed_int_': { 'nt2::Mone<T>()': 'nt2::Zero<T>()',
                              'nt2::One<T>()': 'nt2::Zero<T>()',
                              'nt2::Zero<T>()': 'nt2::Zero<T>()'},
             'unsigned_int_': { 'nt2::One<T>()': 'nt2::Zero<T>()',
                                'nt2::Zero<T>()': 'nt2::Zero<T>()'}},
  'stamp': 'modified by jt the 28/11/2010',
  'tcall': "a0>a1 ? a0-a1 : a1-a0",
  'types': ['real_', 'signed_int_','unsigned_int_'],
  'versn': 0.0}
