{ 'arity': 1,
  'dptch': ['real_', 'unsigned_', 'signed_'],
  'incld': [],
  'norst': False,
  'rnges': { 'default': [['nt2::Valmin<T>()', 'nt2::Valmax<T>()']],
             'double': [['-10.0', '10.0']],
             'float': [['-10.0f', '10.0f']]},
  'rturn': { 'default': 'typename boost::result_of<nt2::meta::floating(T)>::type'},
  'specv': { 'default': { },
             'real_': { 'nt2::Inf<T>()': 'nt2::Zero<r_t>()',
                        'nt2::Minf<T>()': 'nt2::Pi<r_t>()',
                        'nt2::Mone<T>()': 'nt2::Pi<r_t>()',
                        'nt2::Nan<T>()': 'nt2::Nan<r_t>()',
                        'nt2::One<T>()': 'nt2::Zero<r_t>()',
                        'nt2::Zero<T>()': 'nt2::Zero<r_t>()'},
             'signed_int_': { 'nt2::Mone<T>()': 'nt2::Pi<r_t>()',
                              'nt2::One<T>()': 'nt2::Zero<r_t>()',
                              'nt2::Zero<T>()': 'nt2::Zero<r_t>()'},
             'unsigned_int_': { 'nt2::One<T>()': 'nt2::Zero<r_t>()',
                                'nt2::Zero<T>()': 'nt2::Zero<r_t>()'}},
  'stamp': 'modified by jt the 28/11/2010',
  'tcall': 'a0>=0 ? 0 : nt2::Pi<r_t>()',
  'types': ['real_', 'unsigned_int_', 'signed_int_'],
  'version': 0.0}
