[{'functor': {'arity': '2',
              'call_types': [],
              'ret_arity': '0',
              'rturn': {'default': 'typename boost::result_of<nt2::meta::arithmetic(T,T)>::type'},
              'type_defs': [],
              'types': ['real_', 'unsigned_int_', 'signed_int_']},
  'unit': {'global_header': {'first_stamp': 'modified by jt the 01/12/2010',
                             'included': ['#include<nt2/include/functions/ceil.hpp>'],
                             'notes': [],
                             'stamp': 'modified by jt the 13/12/2010'},
           'ranges': {'real_': [['T(-10)', 'T(10)'], ['T(-10)', 'T(10)']],
                      'signed_int_': [['-100', '100'], ['-100', '100']],
                      'unsigned_int_': [['0', '100'], ['0', '100']]},
           'specific_values': {'default': {},
                               'real_': {'4,3': '2',
                                         'nt2::Inf<T>()': 'nt2::Nan<T>()',
                                         'nt2::Minf<T>()': 'nt2::Nan<T>()',
                                         'nt2::Mone<T>()': 'nt2::One<T>()',
                                         'nt2::Nan<T>()': 'nt2::Nan<T>()',
                                         'nt2::One<T>()': 'nt2::One<T>()',
                                         'nt2::Zero<T>()': 'nt2::Nan<T>()'},
                               'signed_int_': {'4,3': '2',
                                               'nt2::Mone<T>()': 'nt2::One<T>()',
                                               'nt2::One<T>()': 'nt2::One<T>()',
                                               'nt2::Zero<T>()': 'nt2::Zero<T>()'},
                               'unsigned_int_': {'4,3': '2',
                                                 'nt2::One<T>()': 'nt2::One<T>()',
                                                 'nt2::Zero<T>()': 'nt2::Zero<T>()'}},
           'verif_test': {'property_call': None,
                          'property_value': {'default': ['r_t(nt2::ceil((1.0*a0)/a1))']},
                          'ulp_thresh': {'default': ['0']}}},
  'version': '0.1'}]