{ 'arity': 2,
  'dptch': ['real_', 'arithmetic_'],
  'incld': ["#include<nt2/include/functions/iround.hpp>",
            "#include<nt2/include/functions/tofloat.hpp>"],
  'norst': False,
  'notes': [],
  'rnges': { 'real_': [['T(-10)', 'T(10)'], ['T(-10)', 'T(10)']],
             'signed_int_': [['-100', '100'], ['1', '100']],
             'unsigned_int_': [['0', '100'], ['1', '100']]},
  'rturn': { 'default':  'typename boost::result_of<nt2::meta::arithmetic(T,T)>::type'},
  'specv': { 'default': { },
             'real_': { 'nt2::Inf<T>()': 'nt2::Nan<r_t>()',
                        'nt2::Minf<T>()': 'nt2::Nan<r_t>()',
                        'nt2::Mone<T>()': 'nt2::One<r_t>()',
                        'nt2::Nan<T>()': 'nt2::Nan<r_t>()',
                        'nt2::One<T>()': 'nt2::One<r_t>()',
                        },
             'signed_int_': { 'nt2::Mone<T>()': 'nt2::One<r_t>()',
                              'nt2::One<T>()': 'nt2::One<r_t>()',
                              },
             'unsigned_int_': { 'nt2::One<T>()': 'nt2::One<r_t>()',
                                }},
  'stamp': 'modified by jt the 01/12/2010',
  'tcall': "nt2::iround(nt2::tofloat(a0)/nt2::tofloat(a1))",
  'types': ['real_', 'unsigned_int_', 'signed_int_'],
  'versn': 0.0}
