{ 'arity': 2,
  'dptch': ['fundamental_'],
  'incld': [],
  'norst': False,
  'notes': [],
  'rnges': { 'real_': [['T(-10)', 'T(10)'], ['T(-10)', 'T(10)']],
             'signed_int_': [['-100', '100'], ['-100', '100']],
             'unsigned_int_': [['0', '100'], ['0', '100']]},
  'rturn': { 'default': 'bool'},
  'specv': { 'default': { },
             'real_': { 'nt2::Inf<T>()': 'false',
                        'nt2::Minf<T>()': 'false',
                        'nt2::Mone<T>()': 'false',
                        'nt2::Nan<T>()': 'false',
                        'nt2::One<T>()': 'false',
                        'nt2::Zero<T>()': 'false',
                        'T(0),T(1)':'true',
                        'T(3),T(0)':'true',
                        },
             'signed_int_': { 'nt2::Mone<T>()': 'false',
                              'nt2::One<T>()': 'false',
                              'nt2::Zero<T>()': 'false'},
             'unsigned_int_': { 'nt2::One<T>()': 'false',
                                'nt2::Zero<T>()': 'false',
                                },
             },
  'stamp': 'modified by jt the 01/12/2010',
  'tcall': {"real_" : None,'default':"(a0!=0)^(a1!=0)"},
  'types': ['real_', 'unsigned_int_', 'signed_int_'],
  'versn': "0.0"}
