{ 'arity': 2,
  'dptch': ['fundamental_'],
  'incld': ['#include <boost/fusion/tuple.hpp>',
            '#include <nt2/include/functions/rem.hpp>',
            '#include <nt2/include/functions/idivfix.hpp>'],
  'norst': False,
  'notes': [],
  'rnges': { 'real_': [['T(-10)', 'T(10)'], ['T(-10)', 'T(10)']],
             'signed_int_': [['-100', '100'], ['-100', '100']],
             'unsigned_int_': [['0', '100'], ['0', '100']]},
  'rturn': { 'default': 'boost::fusion::tuple<T,typename nt2::meta::as_integer<T,signed>::type>'},
  'specv': None,
  'stamp': 'modified by jt the 01/12/2010',
  'tcall': None,
  'tuple': True,
  'tcal0': 'nt2::rem(a0,a1)',
  'tcal1': 'nt2::idivfix(a0,a1)',
  'types': ['real_'],
  'versn': "0.0"}
