{ 'arity': 1,
  'dptch': ['fundamental_'],
  'incld': [],
  'norst': False,
  'notes': [],
  'rnges': { 'real_': [['T(-10)', 'T(10)']],
             'signed_int_': [['-100', '100']],
             'unsigned_int_': [['0', '100']]},
  'rturn': { 'default': 'T'},
  'specv': { 'default': { },
             'real_': { 'nt2::Inf<T>()': 'nt2::Inf<r_t>()',
                        'nt2::Minf<T>()': 'nt2::Minf<r_t>()',
                        'nt2::Mone<T>()': 'nt2::Mone<r_t>()',
                        'nt2::Nan<T>()': 'nt2::Nan<r_t>()',
                        'nt2::One<T>()': 'nt2::One<r_t>()',
                        'nt2::Zero<T>()': 'nt2::Zero<r_t>()',
                        'nt2::Half<T>()': 'nt2::Zero<r_t>()',
                        'nt2::Mhalf<T>()': 'nt2::Zero<r_t>()',
                        'T(1.6)':'2',
                        'T(1.5)':'2',
                        'T(1.4)':'1',
                        'T(2.5)':'2',
                        },
             'signed_int_': { 'nt2::Mone<T>()': 'nt2::Mone<r_t>()',
                              'nt2::One<T>()': 'nt2::One<r_t>()',
                              'nt2::Zero<T>()': 'nt2::Zero<T>()'},
             'unsigned_int_': { 'nt2::One<T>()': 'nt2::One<r_t>()',
                                'nt2::Zero<T>()': 'nt2::Zero<r_t>()'}},
  'stamp': 'modified by jt the 01/12/2010',
  'tcall': {"real_" : "::round(a0)", "default" : "a0",},
  'types': ['real_', 'unsigned_int_', 'signed_int_'],
  'versn': "0.0"}
