{ 'arity': 1,
  'dptch': ['real_', 'arithmetic_'],
  'incld': [],
  'norst': False,
  'notes': [],
  'rnges': { 'real_': [['T(-10)', 'T(10)']],
             'signed_int_': [['-100', '100']],
             'unsigned_int_': [['0', '100']]},
  'rturn': { 'default': 'T'},
  'specv': { 'default': { },
             'real_': { 'nt2::Inf<T>()': 'nt2::Inf<T>()',
                        'nt2::Minf<T>()': 'nt2::Minf<T>()',
                        'nt2::Mone<T>()': 'nt2::Mone<T>()',
                        'nt2::Nan<T>()': 'nt2::Nan<T>()',
                        'nt2::One<T>()': 'nt2::One<T>()',
                        'nt2::Zero<T>()': 'nt2::Zero<T>()',
                        'T(1.1)'        : 'r_t(1)',
                        'T(-1.1)'       : 'r_t(-1)'
},
             'signed_int_': { 'nt2::Mone<T>()': 'nt2::Mone<T>()',
                              'nt2::One<T>()': 'nt2::One<T>()',
                              'nt2::Zero<T>()': 'nt2::Zero<T>()'},
             'unsigned_int_': { 'nt2::One<T>()': 'nt2::One<T>()',
                                'nt2::Zero<T>()': 'nt2::Zero<T>()'}},
  'stamp': 'modified by jt the 01/12/2010',
  'tcall': "(long int)(a0)",
  'types': ['real_', 'unsigned_int_', 'signed_int_'],
  'versn': "0.0"}

