{ 'arity': 1,
  'dptch': ['fundamental_'],
  'incld': [],
  'norst': False,
  'notes': [],
  'rnges': { 'real_': [['T(-10)', 'T(10)']],
             'signed_int_': [['-100', '100']],
             'unsigned_int_': [['0', '100']]},
  'rturn': { 'default': 'boost::fusion::tuple<T,T>'},
  'specv': None,
  'stamp': 'modified by jt the 01/12/2010',
  'tcall': None,
  'types': ['real_'],
  'versn': "0.0"}
