#! /usr/bin/env python
# -*- coding: iso-8859-15  -*-
##############################################################################
#         Copyright 2003 & onward LASMEA UMR 6602 CNRS/Univ. Clermont II
#         Copyright 2009 & onward LRI    UMR 8623 CNRS/Univ Paris Sud XI
#
#          Distributed under the Boost Software License, Version 1.0
#                 See accompanying file LICENSE.txt or copy at
#                     http://www.boost.org/LICENSE_1_0.txt
##############################################################################


"""User utility to comment simd def in usr toolboxes
   usage:
           comment_simd_in_usr_tb

   
"""

import sys
import os
sys.path.insert(0,os.path.join(os.path.dirname(os.path.realpath(__file__)),'../source'))


import sys
import re
from fctor      import Functor
from file_utils import read, write,exist
from mylogging  import Mylogging
from toolbox_list  import Toolboxes
from suppress_simd  import Sup_simd

if __name__ == "__main__" :
    Mylogging.set_level('CRITICAL')
    ts = Toolboxes()
    for tb in ts.get_usr_tb_list() :
##        print "treating toolbox %s" %tb
##        susi=Sup_simd(tb)
##        susi.modify_Cmake_benches_txt()
##        susi.modify_functors_defs()     
sys.path.pop(0)
           
       

