<<<<<<< HEAD
{ 'arity': 2,
  'dptch': ['real_', 'arithmetic_'],
  'incld': [],
  'norst': False,
  'notes': [],
  'rnges': { 'real_': [['T(-10)', 'T(10)'], ['T(-10)', 'T(10)']],
             'signed_int_': [['-100', '100'], ['-100', '100']],
             'unsigned_int_': [['0', '100'], ['0', '100']]},
  'rturn': { 'default': 'T'},
  'specv': { 'default': { },
             'real_': { 'nt2::Inf<T>()': 'nt2::Nan<T>()',
                        'nt2::Minf<T>()': 'nt2::Nan<T>()',
                        'nt2::Mone<T>()': 'nt2::Mone<T>()',
                        'nt2::Nan<T>()': 'nt2::Nan<T>()',
                        'nt2::One<T>()': 'nt2::One<T>()',
                        'nt2::Zero<T>()': 'nt2::Zero<T>()',
                        '3,5':'1',
                        '3,15':'3',
                        '6,15':'3',
                        '120,80':'40',
                        },
             'signed_int_': { 'nt2::Mone<T>()': 'nt2::Mone<T>()',
                              'nt2::One<T>()': 'nt2::One<T>()',
                              'nt2::Zero<T>()': 'nt2::Zero<T>()'},
             'unsigned_int_': { 'nt2::One<T>()': 'nt2::One<T>()',
                                'nt2::Zero<T>()': 'nt2::Zero<T>()'}},
  'stamp': 'modified by jt the 30/11/2010',
  'tcall': None,
  'types': ['real_', 'unsigned_int_', 'signed_int_'],
  'versn': 0.0}
=======
[{'functor': {'arity': '2',
              'call_types': [],
              'ret_arity': '0',
              'rturn': {'default': 'typename boost::result_of<nt2::meta::arithmetic(T)>::type'},
              'type_defs': [],
              'types': ['real_', 'unsigned_int_', 'signed_int_']},
  'unit': {'global_header': {'first_stamp': 'modified by jt the 30/11/2010',
                             'included': [],
                             'notes': [],
                             'stamp': 'modified by jt the 02/01/2011'},
           'ranges': {'real_': [['T(-10)', 'T(10)'], ['T(-10)', 'T(10)']],
                      'signed_int_': [['-100', '100'], ['-100', '100']],
                      'unsigned_int_': [['0', '100'], ['0', '100']]},
           'specific_values': {'default': {},
                               'real_': {'120,80': '40',
                                         '3,15': '3',
                                         '3,5': '1',
                                         '6,15': '3',
                                         'nt2::Inf<T>()': 'nt2::Nan<T>()',
                                         'nt2::Minf<T>()': 'nt2::Nan<T>()',
                                         'nt2::Mone<T>()': 'nt2::Mone<T>()',
                                         'nt2::Nan<T>()': 'nt2::Nan<T>()',
                                         'nt2::One<T>()': 'nt2::One<T>()',
                                         'nt2::Zero<T>()': 'nt2::Zero<T>()'},
                               'signed_int_': {'nt2::Mone<T>()': 'nt2::Mone<T>()',
                                               'nt2::One<T>()': 'nt2::One<T>()',
                                               'nt2::Zero<T>()': 'nt2::Zero<T>()'},
                               'unsigned_int_': {'nt2::One<T>()': 'nt2::One<T>()',
                                                 'nt2::Zero<T>()': 'nt2::Zero<T>()'}},
           'verif_test': {}},
  'version': '0.1'}]
>>>>>>> functor2
