[{'functor': {'arity': '1',
              'call_types': [],
              'ret_arity': '0',
              'rturn': {'default': 'T'},
              'type_defs': [],
              'types': ['real_', 'unsigned_int_', 'signed_int_']},
  'unit': {'global_header': {'first_stamp': 'modified by jt the 01/12/2010',
                             'included': [],
                             'notes': [],
                             'ranges': {'real_': [['T(-10)', 'T(10)']],
                                        'signed_int_': [['-100', '100']],
                                        'unsigned_int_': [['0', '100']]},
                             'specific_values': {'default': {},
                                                 'real_': {'T(1.4)': '1',
                                                           'T(1.5)': '2',
                                                           'T(1.6)': '2',
                                                           'T(2.5)': '2',
                                                           'nt2::Half<T>()': 'nt2::Zero<r_t>()',
                                                           'nt2::Inf<T>()': 'nt2::Inf<r_t>()',
                                                           'nt2::Mhalf<T>()': 'nt2::Zero<r_t>()',
                                                           'nt2::Minf<T>()': 'nt2::Minf<r_t>()',
                                                           'nt2::Mone<T>()': 'nt2::Mone<r_t>()',
                                                           'nt2::Nan<T>()': 'nt2::Nan<r_t>()',
                                                           'nt2::One<T>()': 'nt2::One<r_t>()',
                                                           'nt2::Zero<T>()': 'nt2::Zero<r_t>()'},
                                                 'signed_int_': {'nt2::Mone<T>()': 'nt2::Mone<r_t>()',
                                                                 'nt2::One<T>()': 'nt2::One<r_t>()',
                                                                 'nt2::Zero<T>()': 'nt2::Zero<T>()'},
                                                 'unsigned_int_': {'nt2::One<T>()': 'nt2::One<r_t>()',
                                                                   'nt2::Zero<T>()': 'nt2::Zero<r_t>()'}},
                             'stamp': 'modified by jt the 12/12/2010',
                             'verif_test': {'property_call': None,
                                            'property_value': {'default': [{'default': 'a0',
                                                                            'real_': '::round(a0)'}]},
                                            'ulp_thresh': '0'}}},
  'version': '0.1'}]