string(TOUPPER ${FILE_NAME} FILE_NAME_U)
string(TOUPPER ${TOOLBOX_NAME} TOOLBOX_NAME_U)
file(WRITE "${FILE_NAME}.hpp"
           "//==============================================================================\n"
           "//         Copyright 2003 - 2011   LASMEA UMR 6602 CNRS/Univ. Clermont II       \n"
           "//         Copyright 2009 - 2011   LRI    UMR 8623 CNRS/Univ Paris Sud XI       \n"
           "//                                                                              \n"
           "//          Distributed under the Boost Software License, Version 1.0.          \n"
           "//                 See accompanying file LICENSE.txt or copy at                 \n"
           "//                     http://www.boost.org/LICENSE_1_0.txt                     \n"
           "//==============================================================================\n"
           "#ifndef NT2_TOOLBOX_${TOOLBOX_NAME_U}_CONSTANTS_${FILE_NAME_U}_HPP_INCLUDED\n"
           "#define NT2_TOOLBOX_${TOOLBOX_NAME_U}_CONSTANTS_${FILE_NAME_U}_HPP_INCLUDED\n"
           "#include <nt2/sdk/constant/constant.hpp>\n"
           "\n"
           "namespace nt2\n"
           "{\n"
           "  ${CONTENT}\n"
           "}\n"
           "\n"
           "#endif\n"
          )
