#!/bin/bash

color_option=''
if grep --help | grep -q -e --color
then
  color_option='--color=auto'
fi

if git diff --cached | grep -E '^\+.*'$'\t' > /dev/null
then
cat<<END;
error: tabulations were found in staged changes, which is against
the NT2 coding standards.

If you *really* know what you are doing, you can force this commit
with 'git commit --no-verify'

Incriminated changes:
END
  for i in `git diff --cached --name-only`
  do
    LANG=C git blame $i \
  | sed -r 's@[^(]+\(Not Committed Yet +[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2} [-+0-9]+ +([0-9]+)\) (.*)@'$i':\1: \2@g;tx;d;:x' \
  | GREP_COLOR='1;37;41' grep -F $'\t' $color_option
  done
  exit 1
fi

if git diff --cached | grep -E '^\+.*'$'\r' > /dev/null
then
cat<<END;
error: carriage returns were found in staged changes, which is against
the NT2 coding standards.

If you *really* know what you are doing, you can force this commit
with 'git commit --no-verify'

Incriminated files:
END
  git diff --cached --name-only
  exit 1
fi
