[{'functor': {'arity': '2',
              'call_types': ['T', 'iT'],
              'ret_arity': '0',
              'rturn': {'default': 'T'},
              'type_defs': ['typedef typename nt2::meta::as_integer<T>::type iT;'],
              'types': ['real_']},
  'unit': {'global_header': {'first_stamp': 'modified by jt the 04/12/2010',
                             'included': [],
                             'notes': [],
                             'ranges': {'real_': [['T(-10)', 'T(10)'],
                                                  ['iT(-10)', 'iT(10)']]},
                             'specific_values': None,
                             'stamp': 'modified by jt the 12/12/2010',
                             'verif_test': {'property_call': None,
                                            'property_value': {'default': ['(a1>=0) ? a0*(1<<a1) : a0/(1<<(-a1))']},
                                            'ulp_thresh': '0'}}},
  'version': '0.1'}]