[{'functor': {'arity': '1',
              'call_types': [],
              'ret_arity': '0',
              'rturn': {'default': 'boost::fusion::vector<T,T>'},
              'type_defs': [],
              'types': ['real_', 'unsigned_int_', 'signed_int_']},
  'unit': {'global_header': {'first_stamp': 'modified by jt the 04/12/2010',
                             'included': ['#include <nt2/include/functions/trunc.hpp>',
                                          '#include <nt2/include/functions/frac.hpp>'],
                             'notes': [],
                             'ranges': {'real_': [['T(-10)', 'T(10)']],
                                        'signed_int_': [['-100', '100']],
                                        'unsigned_int_': [['0', '100']]},
                             'specific_values': None,
                             'stamp': 'modified by jt the 12/12/2010',
                             'verif_test': {'property_call': None,
                                            'property_value': {'default': ['nt2::frac(a0)',
                                                                           'nt2::trunc(a0)']},
                                            'ulp_thresh': ['0', '0']}}},
  'version': '0.1'}]