[{'functor': {'arity': '2',
              'call_types': [],
              'ret_arity': '0',
              'rturn': {'default': 'typename boost::result_of<nt2::meta::arithmetic(T,T)>::type'},
              'type_defs': [],
              'types': ['real_', 'unsigned_int_', 'signed_int_']},
  'unit': {'global_header': {'first_stamp': 'modified by jt the 04/12/2010',
                             'included': ['#include <nt2/include/functions/sign.hpp>'],
                             'notes': [],
                             'ranges': {'real_': [['T(-10)', 'T(10)'],
                                                  ['T(-10)', 'T(10)']],
                                        'signed_int_': [['-100', '100'],
                                                        ['-100', '100']],
                                        'unsigned_int_': [['0', '100'],
                                                          ['0', '100']]},
                             'specific_values': {'default': {},
                                                 'real_': {'nt2::Inf<T>()': 'nt2::Inf<r_t>()',
                                                           'nt2::Minf<T>()': 'nt2::Inf<r_t>()',
                                                           'nt2::Mone<T>()': 'nt2::One<r_t>()',
                                                           'nt2::Nan<T>()': 'nt2::Nan<r_t>()',
                                                           'nt2::One<T>()': 'nt2::One<r_t>()',
                                                           'nt2::Zero<T>()': 'nt2::Zero<r_t>()'},
                                                 'signed_int_': {'nt2::Mone<T>()': 'nt2::One<r_t>()',
                                                                 'nt2::One<T>()': 'nt2::One<r_t>()',
                                                                 'nt2::Zero<T>()': 'nt2::Zero<r_t>()'},
                                                 'unsigned_int_': {'nt2::One<T>()': 'nt2::One<r_t>()',
                                                                   'nt2::Zero<T>()': 'nt2::Zero<r_t>()'}},
                             'stamp': 'modified by jt the 12/12/2010',
                             'verif_test': {'property_call': None,
                                            'property_value': {'default': ['nt2::sign(a1)*a0']},
                                            'ulp_thresh': '0'}}},
  'version': '0.1'}]