#! /usr/bin/env python
# -*- coding: iso-8859-15  -*-


"""User utility to create a Nt2 toolbox
   usage:
           create_toolbox <name> [style]
         
   <name> (mandatory) is the name of the toolbox, it must
          a valid C++ variable name (please use lower case)

   [style] is optionnal (default is 'usr') and can take the values
           usr -> the toolbox will live under a the sub-namespace of
                  nt2 of its own name (for instance cephes cosine functor
                  is nt2::cephes::cos)
           sys -> the toolbox will live under the nt2 namespace (for
                  instance trigonometry cosine functor
                  is nt2:cos

           please don't use sys unless you know what you are doing
           and also manage to choose non existing toolbox names for
           your creations.
           It will avoid potential name clashes

"""

import sys
from tbox       import Toolbox
from mylogging  import Mylogging

if __name__ == "__main__" :
    Mylogging.set_level('ERROR')
    length = len(sys.argv)
    if length==1 :
        print __doc__
    else :
        tb_name = sys.argv[1]
        style = 'usr' if length <= 2 else sys.argv[2]
        tb = Toolbox(tb_name,style=style)
        print "creating toolbox %s" %tb.get_tb_name()
        print "with %s style" % tb.get_tb_style() 

