#! /usr/bin/env python
# -*- coding: iso-8859-15  -*-


"""User utility to remove a functor from a given Nt2 toolbox
   usage:
           rm_toolbox <name> <functor_name>
         
   <name> (mandatory) is the name of the existing toolbox

   <functor_name>  (mandatory) is the name of the functor to be removed

"""

import sys
from tbox       import Toolbox
from mylogging  import Mylogging

if __name__ == "__main__" :
    Mylogging.set_level('ERROR')
    length = len(sys.argv)
    if length!=3 :
        print __doc__
    else :
        tb_name = sys.argv[1]
        fct_name = sys.argv[2]       
        fct = Functor(tb_name)
        fct.rmv_functor(fct_name)
