#! /usr/bin/env python
# -*- coding: iso-8859-15  -*-


"""User utility to remove a Nt2 toolbox
   usage:
           rm_toolbox <name> 
         
   <name> (mandatory) is the name of the existing toolbox

"""

import sys
from tbox       import Toolbox
from mylogging  import Mylogging

if __name__ == "__main__" :
    Mylogging.set_level('ERROR')
    length = len(sys.argv)
    if length==1 :
        print __doc__
    else :
        tb_name = sys.argv[1]
        tb = Toolbox(tb_name,mode='modify')
        tb.rm_tbox()
