#! /usr/bin/env python
# -*- coding: iso-8859-15  -*-
##############################################################################
#         Copyright 2003 & onward LASMEA UMR 6602 CNRS/Univ. Clermont II
#         Copyright 2009 & onward LRI    UMR 8623 CNRS/Univ Paris Sud XI
#
#          Distributed under the Boost Software License, Version 1.0
#                 See accompanying file LICENSE.txt or copy at
#                     http://www.boost.org/LICENSE_1_0.txt
##############################################################################


"""User utility to remove a Nt2 toolbox
   usage:
           rm_toolbox <name> 
         
   <name> (mandatory) is the name of the existing toolbox

"""

import sys
import os
sys.path.insert(0,os.path.join(os.path.dirname(os.path.realpath(__file__)),'source'))

from tbox       import Toolbox
from mylogging  import Mylogging

if __name__ == "__main__" :
    Mylogging.set_level('ERROR')
    length = len(sys.argv)
    if length==1 :
        print __doc__
    else :
        tb_name = sys.argv[1]
        tb = Toolbox(tb_name,mode='modify')
        tb.rm_tbox()
sys.path.pop(0)
