{ 'arity': 1,
  'dptch': ['unsigned', 'arithmetic_'],
  'incld': ["#include <nt2/include/functions/bitinteger.hpp>"],
  'norst': False,
  'notes': [],
  'rnges': {
      'int32_t': [['-100', '100']],
      'int64_t': [['-100', '100']],
      'uint32_t': [['0', '100']],
      'uint64_t': [['0', '100']],
      },
  'rturn': { 'default': 'typename nt2::meta::as_real<T>::type'},
  'specv': None,
  'stamp': 'modified by jt the 04/12/2010',
  'tcall': None,
  'verif': "nt2::bitinteger(nt2::bitfloating(a0))",
  'verva': "a0",
  'types': [ 'uint32_t', 'uint64_t', 'int32_t', 'int64_t'],
  'versn': '0.0'}
