{ 'arity': 1,
  'dptch': ['unsigned', 'arithmetic_'],
  'incld': ["#include <nt2/include/functions/bitfloating.hpp>",
            "#include <nt2/sdk/meta/as_integer.hpp>"],
  'norst': False,
  'notes': [],
  'rnges': {'real_': [['T(-10)', 'T(10)']],
      'int32_t': [['-100', '100']],
      'int64_t': [['-100', '100']],
      'uint32_t': [['0', '100']],
      'uint64_t': [['0', '100']],
      },
  'rturn': { 'default': 'typename nt2::meta::as_integer<T>::type'},
  'specv': None,
  'stamp': 'modified by jt the 04/12/2010',
  'tcall': None,
  'verif': "nt2::bitfloating(nt2::bitinteger(a0))",
  'verva': "a0",
  'types': [ 'real_'],
  'versn': '0.0'}

##{ 'arity': 1,
##  'dptch': ['fundamental_'],
##  'incld': [],
##  'norst': False,
##  'notes': [],
##  'rnges': { 'real_': [['T(-10)', 'T(10)']],
##            },
##  'rturn': { 'default': 'typename nt2::meta::as_integer<T>::type'},
##  'specv': None,
##  'stamp': 'modified by jt the 04/12/2010',
##  'verif': "nt2::bitfloating(nt2::bitinteger(a0))",
##  'tcall': None,
##  'verva': "a0",
##  'types': ['real_'],
##  'verif': None,
##  'versn': '0.0'}
