{ 'arity': 1,
  'dptch': ['float', 'double'],
  'incld': ["#include <nt2/include/functions/ilogb.hpp>",
            "#include <nt2/include/functions/abs.hpp>"],
  'norst': False,
  'notes': [],
  'rnges': { 'real_': [['T(-10)', 'T(10)']],
             'signed_int_': [['-100', '100']],
             'unsigned_int_': [['0', '100']]},
  'rturn': { 'default': 'typename boost::result_of<meta::arithmetic(T,T)>::type'},
  'specv': { 'default': { },
             'real_': { #'nt2::Inf<T>()': 'nt2::Inf<r_t>()',
                        'nt2::Minf<T>()': 'nt2::Minf<r_t>()',
                        'nt2::Mone<T>()': 'nt2::Zero<r_t>()',
                        #'nt2::Nan<T>()': 'nt2::Maxexponent<T>()',
                        'nt2::One<T>()': 'nt2::Zero<r_t>()',
                        'nt2::Zero<T>()': 'nt2::Zero<r_t>()'},
             },
  'stamp': 'modified by jt the 04/12/2010',
  'tcall': "a0 ?nt2::ilogb(nt2::abs(a0)):0",
  'types': ['real_'],
  'verif': None,
  'versn': '0.0'}
