{ 'arity': 1,
  'dptch': ['float', 'double'],
  'incld': ["#include <nt2/include/functions/ldexp.hpp>",
            "#include <nt2/include/functions/exponent.hpp>",
            "#include <nt2/include/functions/bits.hpp>"],
  'norst': False,
  'notes': [],
  'rnges': { 'real_': [['T(-10000)', 'T(10000)']]},
  'rturn': { 'default': 'typename nt2::meta::as_integer<T, signed>::type'},
  'specv': None,
  'stamp': 'modified by jt the 04/12/2010',
  'tcall': "nt2::bits(nt2::ldexp(nt2::One<T>(),nt2::exponent(a0)))",
  'types': ['real_'],
  'verif': None,
  'versn': '0.0'}
