{ 'arity': 2,
  'dptch': ['real_', 'arithmetic_'],
  'incld': [],
  'norst': False,
  'notes': [],
  'rnges': { 'real_': [['T(-10)', 'T(10)'], ['iT(-10)', 'iT(10)']],},
  'tpdef': ['typedef typename nt2::meta::as_integer<T>::type iT;'],
  'buftp': ['T','iT'],
  'rturn': { 'default': 'T'},
  'specv': None,
  'stamp': 'modified by jt the 04/12/2010',
  'tcall': "(a1>=0) ? a0*(1<<a1) : a0/(1<<(-a1))",
  'types': ['real_'],
  'verif': None,
  'versn': '0.0'}
