{ 'arity': 1,
  'dptch': ['double', 'float'],
  'incld': ['#include <boost/fusion/tuple.hpp>',
            '#include <nt2/include/functions/mantissa.hpp>',
            '#include <nt2/include/functions/exponent.hpp>'],
  'norst': False,
  'notes': [],
  'rnges': { 'real_': [['T(-10)', 'T(10)']],
             'signed_int_': [['-100', '100']],
             'unsigned_int_': [['0', '100']]},
  'rturn': { 'default': 'boost::fusion::vector<T,typename nt2::meta::as_integer<T,signed>::type>'},
  'specv': None,
  'stamp': 'modified by jt the 04/12/2010',
  'tcall': None,
  'tuple':True,
  'tcal0': 'nt2::mantissa(a0)/2',
  'tcal1': 'nt2::exponent(a0)+1',
  'types': ['real_'],
  'verif': None,
  'versn': '0.0'}
