{ 'arity': 1,
  'dptch': ['fundamental_'],
  'incld': [ "#include <nt2/include/functions/frexp.hpp>"],
  'norst': False,
  'notes': [],
  'rnges': { 'real_': [['T(-10)', 'T(10)']],},
  'rturn': { 'default': 'T'},
  'specv': { 'default': { },
             'real_': { 'nt2::Inf<T>()': 'nt2::One<r_t>()',
                        'nt2::Minf<T>()': 'nt2::Mone<r_t>()',
                        'nt2::Mone<T>()': 'nt2::Mone<r_t>()',
                        #'nt2::Nan<T>()': '-nt2::Two<r_t>()',
                        'nt2::One<T>()': 'nt2::One<r_t>()',
                        'nt2::Zero<T>()': 'nt2::Zero<r_t>()'},
             'signed_int_': { 'nt2::Mone<T>()': 'nt2::Mone<r_t>()',
                              'nt2::One<T>()': 'nt2::One<r_t>()',
                              'nt2::Zero<T>()': 'nt2::Zero<r_t>()'},
             'unsigned_int_': { 'nt2::One<T>()': 'nt2::One<r_t>()',
                                'nt2::Zero<T>()': 'nt2::Zero<r_t>()'}},
  'stamp': 'modified by jt the 04/12/2010',
  'tcall': "boost::fusion::get<0>(nt2::frexp(a0))*2",
  'types': ['real_'],
  'verif': None,
  'versn': '0.0'}
