{ 'arity': 1,
  'dptch': ['fundamental_'],
  'incld': [ '#include <nt2/include/functions/trunc.hpp>',
            '#include <nt2/include/functions/frac.hpp>'],
  'norst': False,
  'notes': [],
  'rnges': { 'real_': [['T(-10)', 'T(10)']],
             'signed_int_': [['-100', '100']],
             'unsigned_int_': [['0', '100']]},
  'rturn': { 'default': 'boost::fusion::vector<T,T>'},
  'specv': None,
  'stamp': 'modified by jt the 04/12/2010',
  'tcall': None,
  'tuple':True,
  'tcal1': 'nt2::trunc(a0)',
  'tcal0': 'nt2::frac(a0)',
  'types': ['real_', 'unsigned_int_', 'signed_int_'],
  'verif': None,
  'versn': '0.0'}
