{ 'arity': 2,
  'dptch': ['float', 'double', 'unsigned_', 'arithmetic_'],
  'incld': [],
  'norst': False,
  'notes': [],
  'rnges': { 'default': [['T(-10)', 'T(10)'], ['T(-10)', 'T(10)']],
             'signed_int_': [['-100', '100'], ['-100', '100']],
             'unsigned_int_': [['0', '100'], ['0', '100']]},
  'rturn': { 'default': 'T'},
  'specv': None,
  'stamp': 'modified by jt the 04/12/2010',
  'tcall': {"float" : "::nextafterf(a0,a1)",
            "double" : "::nextafter(a0,a1)",
            "signed_int_" : '(a1 == a0) ? a0 : (a1 > a0) ? a0+nt2::One<T>() : a0-nt2::One<T>()',
            'unsigned_int_' : '(a1 == a0) ? a0 : (a1 > a0) ? a0+nt2::One<T>() : a0-nt2::One<T>()'
            },
  'types': ['float', 'double', 'unsigned_int_', 'signed_int_'],
  'verif': None,
  'versn': '0.0'}
