{ 'arity': 1,
  'dptch': ['float', 'double', 'arithmetic_'],
  'incld': ['#include <nt2/include/functions/next.hpp>',
            '#include <nt2/sdk/constant/eps_related.hpp>'],
  'norst': False,
  'notes': [],
  'rnges': { 'real_': [['T(-10)', 'T(10)']],
             'signed_int_': [['-100', '100']],
             'unsigned_int_': [['0', '100']]},
  'rturn': { 'default': 'T'},
  'specv': { 'default': { },
             'real_': { 'nt2::Inf<T>()': 'nt2::Nan<r_t>()',
                        'nt2::Minf<T>()': 'nt2::Nan<r_t>()',
                        'nt2::Mone<T>()': 'nt2::Mone<r_t>()+nt2::Eps<r_t>()/2',
                        'nt2::Nan<T>()': 'nt2::Nan<r_t>()',
                        'nt2::One<T>()': 'nt2::One<r_t>()+nt2::Eps<r_t>()',
                        'nt2::Zero<T>()': 'nt2::Mindenormal<T>()'},
             'signed_int_': { 'nt2::Mone<T>()': 'nt2::Zero<r_t>()',
                              'nt2::One<T>()': 'nt2::Two<r_t>()',
                              'nt2::Zero<T>()': 'nt2::One<r_t>()'},
             'unsigned_int_': { 'nt2::One<T>()': 'nt2::Two<r_t>()',
                                'nt2::Zero<T>()': 'nt2::One<r_t>()'}},
  'stamp': 'modified by jt the 04/12/2010',
  'tcall': "nt2::next(a0)",
  'types': ['real_', 'unsigned_int_', 'signed_int_'],
  'verif': None,
  'versn': '0.0'}
