[{'functor': {'arity': '1',
              'call_types': [],
              'ret_arity': '0',
              'rturn': {'default': 'typename boost::result_of<nt2::meta::floating(T)>::type'},
              'type_defs': [],
              'types': ['real_', 'unsigned_int_', 'signed_int_']},
  'unit': {'global_header': {'first_stamp': 'modified by jt the 08/12/2010',
                             'included': ['#include <nt2/include/functions/sqr.hpp>'],
                             'notes': [],
                             'stamp': 'modified by jt the 14/12/2010'},
           'ranges': {'real_': [['T(-10)', 'T(10)']],
                      'signed_int_': [['-100', '100']],
                      'unsigned_int_': [['0', '100']]},
           'specific_values': {'default': {},
                               'real_': {'T(8)': 'T(2)',
                                         'nt2::Inf<T>()': 'nt2::Inf<r_t>()',
                                         'nt2::Minf<T>()': 'nt2::Minf<r_t>()',
                                         'nt2::Mone<T>()': 'nt2::Mone<r_t>()',
                                         'nt2::Nan<T>()': 'nt2::Nan<r_t>()',
                                         'nt2::One<T>()': 'nt2::One<r_t>()',
                                         'nt2::Zero<T>()': 'nt2::Zero<r_t>()'},
                               'signed_int_': {'nt2::Mone<T>()': 'nt2::Mone<r_t>()',
                                               'nt2::One<T>()': 'nt2::One<r_t>()',
                                               'nt2::Zero<T>()': 'nt2::Zero<r_t>()'},
                               'unsigned_int_': {'nt2::One<T>()': 'nt2::One<r_t>()',
                                                 'nt2::Zero<T>()': 'nt2::Zero<r_t>()'}},
           'verif_test': {'property_call': {'default': ['nt2::sqr(nt2::cbrt(a0))*nt2::cbrt(a0)']},
                          'property_value': {'default': ['T(a0)']},
                          'ulp_thresh': {'default': ['1']}}},
  'version': '0.1'}]