[{'functor': {'arity': '1',
              'call_types': [],
              'ret_arity': '0',
              'rturn': {'default': 'typename boost::result_of<nt2::meta::floating(T)>::type'},
              'type_defs': ['#include <nt2/include/functions/sqr.hpp>'],
              'types': ['real_', 'unsigned_int_', 'signed_int_']},
  'unit': {'global_header': {'first_stamp': 'modified by jt the 08/12/2010',
                             'included': ['#include <nt2/include/functions/exp2.hpp>',
                                          '#include <nt2/include/functions/log2.hpp>',
                                          '#include <nt2/include/functions/abs.hpp>'],
                             'notes': [],
                             'stamp': 'modified by jt the 15/12/2010'},
           'ranges': {'real_': [['T(-10)', 'T(10)']],
                      'signed_int_': [['-10', '10']],
                      'unsigned_int_': [['0', '10']]},
           'specific_values': {'default': {},
                               'real_': {'nt2::Inf<T>()': 'nt2::Inf<r_t>()',
                                         'nt2::Minf<T>()': 'nt2::Zero<r_t>()',
                                         'nt2::Mone<T>()': 'nt2::Half<r_t>()',
                                         'nt2::Nan<T>()': 'nt2::Nan<r_t>()',
                                         'nt2::One<T>()': 'nt2::Two<r_t>()',
                                         'nt2::Zero<T>()': 'nt2::One<r_t>()'},
                               'signed_int_': {'nt2::Mone<T>()': 'nt2::Half<r_t>()',
                                               'nt2::One<T>()': 'nt2::Two<r_t>()',
                                               'nt2::Zero<T>()': 'nt2::One<r_t>()'},
                               'unsigned_int_': {'nt2::One<T>()': 'nt2::Two<r_t>()',
                                                 'nt2::Zero<T>()': 'nt2::One<r_t>()'}},
           'verif_test': {'property_call': {'default': ['nt2::log2(nt2::exp2(a0))',
                                                        'nt2::log2(nt2::sqr(a0))']},
                          'property_value': {'default': ['T(a0)','2*log2(nt2::abs(a0))']},
                          'ulp_thresh': {'default': ['3','3']}}},
  'version': '0.1'}]
