[{'functor': {'arity': '1',
              'call_types': [],
              'ret_arity': '0',
              'rturn': {'default': 'typename nt2::meta::as_integer<T>::type'},
              'type_defs': [],
              'types': ['real_']},
  'unit': {'global_header': {'first_stamp': 'modified by jt the 04/12/2010',
                             'included': ['#include <nt2/include/functions/bitfloating.hpp>',
                                          '#include <nt2/sdk/meta/as_integer.hpp>'],
                             'notes': [],
                             'ranges': {'int32_t': [['-100', '100']],
                                        'int64_t': [['-100', '100']],
                                        'real_': [['T(-10)', 'T(10)']],
                                        'uint32_t': [['0', '100']],
                                        'uint64_t': [['0', '100']]},
                             'specific_values': None,
                             'stamp': 'modified by jt the 12/12/2010',
                             'verif_test': {}}},
  'version': '0.1'}]